// RocketAXITileTop_bb.v — black-box declaration of the hardened 2-port Rocket macro (axi5)
// for chip-level synthesis. Physical view = ip/rocket_axitile_v1/{lef,gds,lib}.
// Port widths verbatim from the signed-off netlist (mem_axi4 32-bit addr, mmio_axi4 31-bit addr).
(* blackbox *)
module RocketAXITileTop (
    input  wire        clock,
    input  wire        reset,
    // ---- mem_axi4_0 (cacheable, 32-bit addr) ----
    input  wire        mem_axi4_0_aw_ready,
    output wire        mem_axi4_0_aw_valid,
    output wire [3:0]  mem_axi4_0_aw_bits_id,
    output wire [31:0] mem_axi4_0_aw_bits_addr,
    output wire [7:0]  mem_axi4_0_aw_bits_len,
    output wire [2:0]  mem_axi4_0_aw_bits_size,
    output wire [1:0]  mem_axi4_0_aw_bits_burst,
    output wire        mem_axi4_0_aw_bits_lock,
    output wire [3:0]  mem_axi4_0_aw_bits_cache,
    output wire [2:0]  mem_axi4_0_aw_bits_prot,
    output wire [3:0]  mem_axi4_0_aw_bits_qos,
    input  wire        mem_axi4_0_w_ready,
    output wire        mem_axi4_0_w_valid,
    output wire [63:0] mem_axi4_0_w_bits_data,
    output wire [7:0]  mem_axi4_0_w_bits_strb,
    output wire        mem_axi4_0_w_bits_last,
    output wire        mem_axi4_0_b_ready,
    input  wire        mem_axi4_0_b_valid,
    input  wire [3:0]  mem_axi4_0_b_bits_id,
    input  wire [1:0]  mem_axi4_0_b_bits_resp,
    input  wire        mem_axi4_0_ar_ready,
    output wire        mem_axi4_0_ar_valid,
    output wire [3:0]  mem_axi4_0_ar_bits_id,
    output wire [31:0] mem_axi4_0_ar_bits_addr,
    output wire [7:0]  mem_axi4_0_ar_bits_len,
    output wire [2:0]  mem_axi4_0_ar_bits_size,
    output wire [1:0]  mem_axi4_0_ar_bits_burst,
    output wire        mem_axi4_0_ar_bits_lock,
    output wire [3:0]  mem_axi4_0_ar_bits_cache,
    output wire [2:0]  mem_axi4_0_ar_bits_prot,
    output wire [3:0]  mem_axi4_0_ar_bits_qos,
    output wire        mem_axi4_0_r_ready,
    input  wire        mem_axi4_0_r_valid,
    input  wire [3:0]  mem_axi4_0_r_bits_id,
    input  wire [63:0] mem_axi4_0_r_bits_data,
    input  wire [1:0]  mem_axi4_0_r_bits_resp,
    input  wire        mem_axi4_0_r_bits_last,
    // ---- mmio_axi4_0 (uncached, 31-bit addr) ----
    input  wire        mmio_axi4_0_aw_ready,
    output wire        mmio_axi4_0_aw_valid,
    output wire [3:0]  mmio_axi4_0_aw_bits_id,
    output wire [30:0] mmio_axi4_0_aw_bits_addr,
    output wire [7:0]  mmio_axi4_0_aw_bits_len,
    output wire [2:0]  mmio_axi4_0_aw_bits_size,
    output wire [1:0]  mmio_axi4_0_aw_bits_burst,
    output wire        mmio_axi4_0_aw_bits_lock,
    output wire [3:0]  mmio_axi4_0_aw_bits_cache,
    output wire [2:0]  mmio_axi4_0_aw_bits_prot,
    output wire [3:0]  mmio_axi4_0_aw_bits_qos,
    input  wire        mmio_axi4_0_w_ready,
    output wire        mmio_axi4_0_w_valid,
    output wire [63:0] mmio_axi4_0_w_bits_data,
    output wire [7:0]  mmio_axi4_0_w_bits_strb,
    output wire        mmio_axi4_0_w_bits_last,
    output wire        mmio_axi4_0_b_ready,
    input  wire        mmio_axi4_0_b_valid,
    input  wire [3:0]  mmio_axi4_0_b_bits_id,
    input  wire [1:0]  mmio_axi4_0_b_bits_resp,
    input  wire        mmio_axi4_0_ar_ready,
    output wire        mmio_axi4_0_ar_valid,
    output wire [3:0]  mmio_axi4_0_ar_bits_id,
    output wire [30:0] mmio_axi4_0_ar_bits_addr,
    output wire [7:0]  mmio_axi4_0_ar_bits_len,
    output wire [2:0]  mmio_axi4_0_ar_bits_size,
    output wire [1:0]  mmio_axi4_0_ar_bits_burst,
    output wire        mmio_axi4_0_ar_bits_lock,
    output wire [3:0]  mmio_axi4_0_ar_bits_cache,
    output wire [2:0]  mmio_axi4_0_ar_bits_prot,
    output wire [3:0]  mmio_axi4_0_ar_bits_qos,
    output wire        mmio_axi4_0_r_ready,
    input  wire        mmio_axi4_0_r_valid,
    input  wire [3:0]  mmio_axi4_0_r_bits_id,
    input  wire [63:0] mmio_axi4_0_r_bits_data,
    input  wire [1:0]  mmio_axi4_0_r_bits_resp,
    input  wire        mmio_axi4_0_r_bits_last
);
endmodule
