// RocketAXITileTop_stub.sv
// Black-box stub of the hardened Rocket tile macro (axi5 signoff) for LINT/elaboration
// of aurora_soc_top_chip only. Port list + widths taken verbatim from the signed-off
// netlist: openlane/rocket/rocket_axitile/runs/axi5/results/synthesis/RocketAXITileTop.v
// (macro perspective: aw/ar/w buses are OUTPUTS, b/r are INPUTS).
// NOT for synthesis — the real macro GDS/LEF/lib is used at chip PnR.
`timescale 1ns/1ps

module RocketAXITileTop (
    input  wire        clock,
    input  wire        reset,

    // ---- mem_axi4_0 (cacheable, 32-bit addr) ----
    input  wire        mem_axi4_0_aw_ready,
    output wire        mem_axi4_0_aw_valid,
    output wire [3:0]  mem_axi4_0_aw_bits_id,
    output wire [31:0] mem_axi4_0_aw_bits_addr,
    output wire [7:0]  mem_axi4_0_aw_bits_len,
    output wire [2:0]  mem_axi4_0_aw_bits_size,
    output wire [1:0]  mem_axi4_0_aw_bits_burst,
    output wire        mem_axi4_0_aw_bits_lock,
    output wire [3:0]  mem_axi4_0_aw_bits_cache,
    output wire [2:0]  mem_axi4_0_aw_bits_prot,
    output wire [3:0]  mem_axi4_0_aw_bits_qos,
    input  wire        mem_axi4_0_w_ready,
    output wire        mem_axi4_0_w_valid,
    output wire [63:0] mem_axi4_0_w_bits_data,
    output wire [7:0]  mem_axi4_0_w_bits_strb,
    output wire        mem_axi4_0_w_bits_last,
    output wire        mem_axi4_0_b_ready,
    input  wire        mem_axi4_0_b_valid,
    input  wire [3:0]  mem_axi4_0_b_bits_id,
    input  wire [1:0]  mem_axi4_0_b_bits_resp,
    input  wire        mem_axi4_0_ar_ready,
    output wire        mem_axi4_0_ar_valid,
    output wire [3:0]  mem_axi4_0_ar_bits_id,
    output wire [31:0] mem_axi4_0_ar_bits_addr,
    output wire [7:0]  mem_axi4_0_ar_bits_len,
    output wire [2:0]  mem_axi4_0_ar_bits_size,
    output wire [1:0]  mem_axi4_0_ar_bits_burst,
    output wire        mem_axi4_0_ar_bits_lock,
    output wire [3:0]  mem_axi4_0_ar_bits_cache,
    output wire [2:0]  mem_axi4_0_ar_bits_prot,
    output wire [3:0]  mem_axi4_0_ar_bits_qos,
    output wire        mem_axi4_0_r_ready,
    input  wire        mem_axi4_0_r_valid,
    input  wire [3:0]  mem_axi4_0_r_bits_id,
    input  wire [63:0] mem_axi4_0_r_bits_data,
    input  wire [1:0]  mem_axi4_0_r_bits_resp,
    input  wire        mem_axi4_0_r_bits_last,

    // ---- mmio_axi4_0 (uncached, 31-bit addr) ----
    input  wire        mmio_axi4_0_aw_ready,
    output wire        mmio_axi4_0_aw_valid,
    output wire [3:0]  mmio_axi4_0_aw_bits_id,
    output wire [30:0] mmio_axi4_0_aw_bits_addr,
    output wire [7:0]  mmio_axi4_0_aw_bits_len,
    output wire [2:0]  mmio_axi4_0_aw_bits_size,
    output wire [1:0]  mmio_axi4_0_aw_bits_burst,
    output wire        mmio_axi4_0_aw_bits_lock,
    output wire [3:0]  mmio_axi4_0_aw_bits_cache,
    output wire [2:0]  mmio_axi4_0_aw_bits_prot,
    output wire [3:0]  mmio_axi4_0_aw_bits_qos,
    input  wire        mmio_axi4_0_w_ready,
    output wire        mmio_axi4_0_w_valid,
    output wire [63:0] mmio_axi4_0_w_bits_data,
    output wire [7:0]  mmio_axi4_0_w_bits_strb,
    output wire        mmio_axi4_0_w_bits_last,
    output wire        mmio_axi4_0_b_ready,
    input  wire        mmio_axi4_0_b_valid,
    input  wire [3:0]  mmio_axi4_0_b_bits_id,
    input  wire [1:0]  mmio_axi4_0_b_bits_resp,
    input  wire        mmio_axi4_0_ar_ready,
    output wire        mmio_axi4_0_ar_valid,
    output wire [3:0]  mmio_axi4_0_ar_bits_id,
    output wire [30:0] mmio_axi4_0_ar_bits_addr,
    output wire [7:0]  mmio_axi4_0_ar_bits_len,
    output wire [2:0]  mmio_axi4_0_ar_bits_size,
    output wire [1:0]  mmio_axi4_0_ar_bits_burst,
    output wire        mmio_axi4_0_ar_bits_lock,
    output wire [3:0]  mmio_axi4_0_ar_bits_cache,
    output wire [2:0]  mmio_axi4_0_ar_bits_prot,
    output wire [3:0]  mmio_axi4_0_ar_bits_qos,
    output wire        mmio_axi4_0_r_ready,
    input  wire        mmio_axi4_0_r_valid,
    input  wire [3:0]  mmio_axi4_0_r_bits_id,
    input  wire [63:0] mmio_axi4_0_r_bits_data,
    input  wire [1:0]  mmio_axi4_0_r_bits_resp,
    input  wire        mmio_axi4_0_r_bits_last
);
    // Tie all macro outputs to 0 (black box — no behaviour for lint).
    assign mem_axi4_0_aw_valid = 1'b0, mem_axi4_0_aw_bits_id = '0, mem_axi4_0_aw_bits_addr = '0,
           mem_axi4_0_aw_bits_len = '0, mem_axi4_0_aw_bits_size = '0, mem_axi4_0_aw_bits_burst = '0,
           mem_axi4_0_aw_bits_lock = 1'b0, mem_axi4_0_aw_bits_cache = '0, mem_axi4_0_aw_bits_prot = '0,
           mem_axi4_0_aw_bits_qos = '0, mem_axi4_0_w_valid = 1'b0, mem_axi4_0_w_bits_data = '0,
           mem_axi4_0_w_bits_strb = '0, mem_axi4_0_w_bits_last = 1'b0, mem_axi4_0_b_ready = 1'b0,
           mem_axi4_0_ar_valid = 1'b0, mem_axi4_0_ar_bits_id = '0, mem_axi4_0_ar_bits_addr = '0,
           mem_axi4_0_ar_bits_len = '0, mem_axi4_0_ar_bits_size = '0, mem_axi4_0_ar_bits_burst = '0,
           mem_axi4_0_ar_bits_lock = 1'b0, mem_axi4_0_ar_bits_cache = '0, mem_axi4_0_ar_bits_prot = '0,
           mem_axi4_0_ar_bits_qos = '0, mem_axi4_0_r_ready = 1'b0;
    assign mmio_axi4_0_aw_valid = 1'b0, mmio_axi4_0_aw_bits_id = '0, mmio_axi4_0_aw_bits_addr = '0,
           mmio_axi4_0_aw_bits_len = '0, mmio_axi4_0_aw_bits_size = '0, mmio_axi4_0_aw_bits_burst = '0,
           mmio_axi4_0_aw_bits_lock = 1'b0, mmio_axi4_0_aw_bits_cache = '0, mmio_axi4_0_aw_bits_prot = '0,
           mmio_axi4_0_aw_bits_qos = '0, mmio_axi4_0_w_valid = 1'b0, mmio_axi4_0_w_bits_data = '0,
           mmio_axi4_0_w_bits_strb = '0, mmio_axi4_0_w_bits_last = 1'b0, mmio_axi4_0_b_ready = 1'b0,
           mmio_axi4_0_ar_valid = 1'b0, mmio_axi4_0_ar_bits_id = '0, mmio_axi4_0_ar_bits_addr = '0,
           mmio_axi4_0_ar_bits_len = '0, mmio_axi4_0_ar_bits_size = '0, mmio_axi4_0_ar_bits_burst = '0,
           mmio_axi4_0_ar_bits_lock = 1'b0, mmio_axi4_0_ar_bits_cache = '0, mmio_axi4_0_ar_bits_prot = '0,
           mmio_axi4_0_ar_bits_qos = '0, mmio_axi4_0_r_ready = 1'b0;
endmodule
