-I/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/include
-I/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/vendor/pulp-platform/common_cells/include
-I/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/vendor/pulp-platform/axi/include
+define+VERILATOR
+define+SYNTHESIS
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/include/config_pkg.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6_resolved_cfg_pkg.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/include/cv64a6_imafdc_sv39_config_pkg.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/include/riscv_pkg.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/include/build_config_pkg.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/include/ariane_pkg.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/include/std_cache_pkg.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/include/wt_cache_pkg.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/include/triggers_pkg.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/include/aes_pkg.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/vendor/pulp-platform/common_cells/src/cf_math_pkg.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/vendor/pulp-platform/common_cells/src/fifo_v3.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/vendor/pulp-platform/common_cells/src/lzc.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/vendor/pulp-platform/common_cells/src/rr_arb_tree.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/vendor/pulp-platform/common_cells/src/spill_register.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/vendor/pulp-platform/common_cells/src/stream_arbiter.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/vendor/pulp-platform/common_cells/src/stream_arbiter_flushable.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/vendor/pulp-platform/common_cells/src/stream_demux.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/vendor/pulp-platform/common_cells/src/stream_mux.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/vendor/pulp-platform/common_cells/src/popcount.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/vendor/pulp-platform/common_cells/src/onehot_to_bin.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/vendor/pulp-platform/common_cells/src/shift_reg.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/vendor/pulp-platform/common_cells/src/lfsr.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/vendor/pulp-platform/common_cells/src/delta_counter.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/vendor/pulp-platform/common_cells/src/counter.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/vendor/pulp-platform/common_cells/src/fall_through_register.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/vendor/pulp-platform/common_cells/src/stream_fifo.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/vendor/pulp-platform/axi/src/axi_pkg.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/common/local/util/sram.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/common/local/util/sram_cache.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/src/fpnew_pkg.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/src/fpnew_cast_multi.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/src/fpnew_classifier.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/clk/rtl/gated_clk_cell.v
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ctrl.v
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ff1.v
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_pack_single.v
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_prepare.v
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_round_single.v
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_special.v
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_srt_single.v
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_top.v
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_dp.v
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_frbus.v
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_src_type.v
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_ctrl.v
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_double.v
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_ff1.v
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_pack.v
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_prepare.v
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_round.v
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_scalar_dp.v
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_bound_table.v
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_with_sqrt.v
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt.v
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_top.v
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/src/fpnew_divsqrt_th_32.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/src/fpnew_divsqrt_th_64_multi.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/src/fpnew_divsqrt_multi.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/src/fpnew_fma_multi.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/src/fpnew_fma.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/src/fpnew_noncomp.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/src/fpnew_opgroup_block.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/src/fpnew_opgroup_fmt_slice.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/src/fpnew_opgroup_multifmt_slice.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/src/fpnew_rounding.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/src/fpnew_top.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/control_mvp.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/fpu_wrap.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/pmp/src/pmp_entry.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/pmp/src/pmp.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cva6_mmu/cva6_tlb.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cva6_mmu/cva6_ptw.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cva6_mmu/cva6_shared_tlb.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cva6_mmu/cva6_mmu.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cache_subsystem/wt_dcache_ctrl.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cache_subsystem/wt_dcache_mem.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cache_subsystem/wt_dcache_missunit.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cache_subsystem/wt_dcache_wbuffer.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cache_subsystem/wt_dcache.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cache_subsystem/wt_axi_adapter.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cache_subsystem/cva6_icache.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cache_subsystem/cva6_icache_axi_wrapper.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cache_subsystem/wt_cache_subsystem.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/frontend/btb.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/frontend/bht.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/frontend/ras.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/frontend/instr_scan.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/frontend/instr_queue.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/frontend/frontend.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/compressed_decoder.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/decoder.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/scoreboard.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/alu.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/serdiv.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/multiplier.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/mult.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/branch_unit.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/load_unit.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/store_unit.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/store_buffer.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/lsu_bypass.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/load_store_unit.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/csr_regfile.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/commit_stage.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/controller.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/issue_read_operands.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/issue_stage.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/id_stage.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/ex_stage.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/instr_realign.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/perf_counters.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/axi_shim.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cva6_fifo_v3.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/ariane_regfile_ff.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cva6_accel_first_pass_decoder_stub.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cvxif_fu.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/raw_checker.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6/core/cva6.sv
/home/yashwanth/aurora_v1/rtl/cpu_cluster/cva6_axi_wrapper.sv
